# ==========================================
# Phase 1: Dependencies (deps)
# Only installs node_modules to maximize caching
# ==========================================
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy package descriptors
COPY package.json package-lock.json ./
RUN npm ci

# ==========================================
# Phase 2: Builder (builder)
# Compiles the Next.js application
# ==========================================
FROM node:20-alpine AS builder
WORKDIR /app

# Copy deps from Phase 1
COPY --from=deps /app/node_modules ./node_modules
# Copy all source files
COPY . .

# Run the production build.
# This respects next.config.ts `output: 'standalone'`
RUN npm run build

# ==========================================
# Phase 3: Runner (runner)
# Minimal, secure production runtime
# ==========================================
FROM node:20-alpine AS runner
WORKDIR /app

# Set production environment
ENV NODE_ENV production
# Disable telemetry
ENV NEXT_TELEMETRY_DISABLED 1

# Create non-root user for security
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Set correct permissions
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Automatically leverage output traces to reduce image size
# Copy public folder for static assets
COPY --from=builder /app/public ./public

# Set the correct permission for prerender cache
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Switch to non-root user
USER nextjs

# Listen across all network interfaces for Cloud Run mapping
ENV HOSTNAME "0.0.0.0"

# Start the server (uses server.js generated by standalone mode)
# In Cloud Run, PORT is injected dynamically at runtime
EXPOSE 3000
CMD ["node", "server.js"]
